name: docs
channels:
  - conda-forge
  - defaults
dependencies:
    # Base depends
  - python
  - pip
  - numpy
  - pytest
  - mdanalysis
  - nglview
  - nbsphinx
  - ipython
  - plotly
  - sphinx_rtd_theme
  - scipy==1.12.0


    # Pip-only installs
  #- pip:
