name: docs
channels:
  - conda-forge
  - defaults
dependencies:
    # Base depends
  - python>=3.11
  - pip
  - numpy>=2.2
  - pytest
  - mdanalysis>=2.8
  - nglview
  - nbsphinx
  - ipython
  - plotly
  - sphinx_rtd_theme
  - scipy


    # Pip-only installs
  #- pip:
